# Generated by Django 3.2.23 on 2025-04-10 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='website',
            name='business_name',
            field=models.CharField(default='New Business', max_length=255),
        ),
        migrations.AddField(
            model_name='website',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='website',
            name='description',
            field=models.TextField(default='Description'),
        ),
        migrations.AddField(
            model_name='website',
            name='location',
            field=models.CharField(default='Location', max_length=255),
        ),
        migrations.AlterField(
            model_name='website',
            name='business_type',
            field=models.CharField(default='Business', max_length=100),
        ),
        migrations.AlterField(
            model_name='website',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='industry',
            field=models.CharField(default='Industry', max_length=100),
        ),
        migrations.AlterField(
            model_name='website',
            name='user_email',
            field=models.CharField(default='user@example.com', max_length=255),
        ),
    ]
