# Generated by Django 4.2.20 on 2025-04-10 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='industry',
            new_name='business_name',
        ),
        migrations.AddField(
            model_name='website',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='website',
            name='location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='website',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
