# Generated by Django 4.2.20 on 2025-04-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20250410_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='color_scheme',
            field=models.CharField(default='modern', max_length=100),
        ),
        migrations.AddField(
            model_name='website',
            name='font_style',
            field=models.CharField(default='sans-serif', max_length=100),
        ),
        migrations.AddField(
            model_name='website',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='website',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='website',
            name='layout_style',
            field=models.CharField(default='responsive', max_length=100),
        ),
        migrations.AddField(
            model_name='website',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='theme_version',
            field=models.IntegerField(default=1),
        ),
    ]
