# Generated by Django 3.2.25 on 2025-04-11 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_industry_website_business_name_and_more'),
        ('main', '0003_website_color_scheme_website_font_style_and_more'),
    ]

    operations = [
    ]
