# Generated by Django 3.2.25 on 2025-04-11 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_merge_20250411_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='industry',
            field=models.CharField(default='Industry', max_length=100),
        ),
        migrations.AlterField(
            model_name='website',
            name='business_name',
            field=models.CharField(default='New Business', max_length=255),
        ),
        migrations.AlterField(
            model_name='website',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='website',
            name='description',
            field=models.TextField(default='Description'),
        ),
        migrations.AlterField(
            model_name='website',
            name='location',
            field=models.CharField(default='Location', max_length=255),
        ),
    ]
